# This Docker Compose file defines a set of services for a microservices architecture.
# It includes services for MongoDB, ZooKeeper, Kafka, and various API services.

networks:
  ev:
    name: "ev"
    driver: bridge

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - "ev"
    restart: unless-stopped

  # ZooKeeper service
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: "zookeeper"
    ports:
      - 2181:2181
    networks:
      - "ev"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # Kafka service
  kafka:
    image: bitnami/kafka:latest
    container_name: "kafka"
    ports:
      - 9092:9092
    networks:
      - "ev"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_RESTART_ATTEMPTS=10
      - KAFKA_RESTART_DELAY=5
      - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0

  # Microservices
  users:
    build: ./api-users
    restart: always
    env_file:
      - ./api-users/.env
    networks:
      - "ev"
    depends_on:
      - kafka

  products:
    build: ./api-product
    restart: always
    env_file:
      - ./api-product/.env
    networks:
      - ev
    depends_on:
      - kafka

  inventory:
    build: ./api-inventory
    restart: always
    env_file:
      - ./api-inventory/.env
    networks:
      - ev
    depends_on:
      - kafka

  order:
    build: ./api-orders
    restart: always
    env_file:
      - ./api-orders/.env
    networks:
      - ev
    depends_on:
      - kafka

  payment:
    build: ./api-payment
    restart: always
    env_file:
      - ./api-payment/.env
    networks:
      - ev
    depends_on:
      - kafka

  # Api gateway
  gateway:
    build: ./api-gateway
    restart: always
    env_file:
      - ./api-gateway/.env
    ports:
      - "3000:3000"
    networks:
      - ev
    depends_on:
      - kafka
    hostname: gateway
